### ISSUE TITLE
Port over and hook up integration actions

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-react#129]
* [x] Start integration
* [x] Stop integration
* [x] Export
* [x] Delete integration
* [ ] CI/CD -> link to a new CI/CD tab under integration details

**Comment by gashcrumb** [comment]
@dongniwang the plan was to move the CI/CD dialog to a tab in the integration detail page, right?  Just going off memory, I'd like to get a placeholder section started as part of this.

**Comment by dongniwang** [comment]
hey @gashcrumb - I can't remember if we decided on a new tab or something in the Settings area. Depends on how we envision this feature will work in the future. What do you think? @gaughan @dhirajsb

**Comment by gashcrumb** [comment]
Ah I see, we added a separate management page to manage the tags vs baking all of it into the dialog, lemme [put the invision link here](https://redhat.invisionapp.com/share/36QTHNFFCUB#/screens/350160524) so I don't forget :-)

**Comment by gashcrumb** [comment]
Have to defer the CI/CD link for now.
