### ISSUE TITLE
Port over OAuth-based connection creation

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-react#136]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Here's the original designs:
https://github.com/syndesisio/syndesis-react/blob/master/ux/designs/oauth/oauth.md

Original design proposal:
https://github.com/syndesisio/syndesis-react/blob/master/project/proposals/029_030-credentials.md

Old UI links:
* The old UI would fetch the connector definition, and then [fetch credentials](https://github.com/syndesisio/syndesis-react/blob/master/app/ui/src/app/connections/create-page/current-connection.ts#L264)
* If the backend response indicates that the connector has oauth credentials configured, the old UI would show [this button](https://github.com/syndesisio/syndesis-react/blob/master/app/ui/src/app/connections/create-page/configure-fields/configure-fields.component.html#L29-L42)
* Clicking that button makes [this function](https://github.com/syndesisio/syndesis-react/blob/master/app/ui/src/app/store/connector/connector.service.ts#L37) happen, which initiates the oauth flow.  Note that the app encodes whatever state is required into that redirect URL in the document hash.  ALso this request goes to our backend, who response with a 302 redirect I believe.
* The user goes off to Twitter or Salesforce or whatever and then is redirected back to our app
* The create connection wizard decodes the state from the document hash, in the old app's case it actually just encodes the selected connector ID, and so just decodes when the create page component loads [here](https://github.com/syndesisio/syndesis-react/blob/master/app/ui/src/app/connections/create-page/create-page.component.ts#L231-L235) and sets it's state accordingly.
* The app then moves to the "review" step and things are pretty normal from there.  The difference being we don't need to set the `configuredProperties` on the connection.

**Comment by mmelko** [comment]
Hi @gashcrumb. Any update od this? I'd expect this is part of https://trello.com/c/lGoR5Z7o/16-m-connection-creation.

**Comment by gashcrumb** [comment]
One other thing to be aware of, the connection detail page is different for a connection with oauth enabled:

![image](https://user-images.githubusercontent.com/351660/58958008-e4210680-876f-11e9-93e5-f3b753038ae8.png)

I'm not sure what's up with the disabled validate button.  The 'Reconnect' button was added later on and allows you to refresh the authorization token.  Might need to pick @zregvart's brain on that one I think.

**Comment by zregvart** [comment]
I think we have most of this done, one bit that recently popped in is syndesisio/syndesis#5582 does it make sense to work on it under this issue or should I open a new one?

cc @paoloantinori

**Comment by paoloantinori** [comment]
so this was more a Feature issue. we can say that we have the feature, despite bugs.

So it's better to work directly on  #5582 since it's also already monitored by qe.
