### ISSUE TITLE
Research how to handle extensions adding functionality to the UI

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-react#14]
In the current Syndesis console an extension can provide a connector or a new step kind in the editor.  Some example extensions are held here -> https://github.com/syndesisio/syndesis-extensions

Connectors and steps added this way appear in the UI the same as our provided connectors and steps.  They can use the same JSON schema to leverage the UI's dynamic form service to provide a generated interface for the user to configure the step or extension.

If we go in a different direction than dynamic forms then we'll need to figure out a method for extensions to be able to provide interfaces.

@riccardo-forina FYI

**Comment by riccardo-forina** [comment]
Perhaps we should build something akin what we have today with the dynamic forms, for this use-case and to allow adding "things" from the BE side with low-to-no impact in the frontend, knowing that we can specialize the forms we need to specialize by adding the proper `if` in the code

**Comment by gashcrumb** [comment]
Yeah, after closing #3 there I realized that we still are going to need some functionality for some of the connectors as there's cases where it's not possible to provide all the configuration in one step, i.e. the first form page influences what you see on the next page.

**Comment by gashcrumb** [comment]
I feel like we don't need this issue open.
