### ISSUE TITLE
Can't add latest patternfly/react-core in syndesis/ui

### ISSUE THREAD

**Issue by seanforyou23** [syndesisio/syndesis-react#143]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Unable to add `@patternfly/react-core` as a dependency to the `@syndesis/ui` package. When I do, and then attempt to perform a build, I receive the following error;

<img width="1210" alt="Screen Shot 2019-04-10 at 2 42 17 PM" src="https://user-images.githubusercontent.com/5942899/56151043-564e4980-5f7e-11e9-8062-3920eb92744f.png">

FWIW this worked before (recently) when we were POCing the AlertGroup component, maybe it's related to the move toward monorepo?

I've checked with others from the PF team and they've confirmed the ability to add latest react-core to a sub package in a monorepo/lerna structured app, so thinking the issue may be on our end.

**Comment by riccardo-forina** [comment]
Did you check out #140? I open that to give you a working starting point for this. Problem was yarn upgrading typescript to v3.4 which isn’t playing nice some bits of our codebase

**Comment by seanforyou23** [comment]
Thx @riccardo-forina - hadn't seen that yet. I'll give it a run here in just a bit!
