### ISSUE TITLE
Add autoform link to storybook

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-react#159]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Definitely need to add a link to autoform's storybook to the top-level page that links to the staging app and storybooks for documentation and examination purposes.

**Comment by riccardo-forina** [comment]
🤦‍♂️ it was there, I removed it instead of the app one (which is useless).

**Comment by gashcrumb** [comment]
Ah okay cool, well it should be an easy fix :-)

**Comment by gashcrumb** [comment]
Fixed in #170
