### ISSUE TITLE
Create "can't talk to the server" error page

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-react#168]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
We're accumulating TODO pages such as:

![image](https://user-images.githubusercontent.com/351660/56585136-397fca80-65ab-11e9-8793-fc187677298f.png)

When the UI is unable to talk to the backend on a given view.

We could use a generic error page/element for this.  Probably an element.

@dongniwang @seanforyou23 is there a patternfly example you could link here maybe?

**Comment by gashcrumb** [comment]
I've been directed to the 404 page to use as a basis, so I'll run with that :running_man:

**Comment by dongniwang** [comment]
Sorry late to comment here. What do you mean by "can't talk to server" error page? When will this happen normally?

**Comment by gashcrumb** [comment]
it's like whenever the UI can't talk to the backend.  In the old app there was that persistent toast notification that could pop up here and there.  But the old app would either just show a spinner forever, or look like it was connected.  In the case of the react codebase the views currently trigger fetching data from the server more often, which can have an immediate impact on the UI if a fetch fails.

Of course, since implementing this and merging it, staging has been pretty stable so I haven't had a chance to see what happens in the wild :-)

**Comment by dongniwang** [comment]
@gashcrumb - I was going to get the screenshot with that persistent toast notification and asked you if that's the same thing! 

Cool, yeah, definitely no toast notification as that's not helping at all...so is there any button on the 404 page to help redirect the users? does the 404 takes over the entire screen or they can still get to the menu?

**Comment by gashcrumb** [comment]
So on the first pass it'll occupy the area of the affected component, so like on the integrations page it'll probably be the app area other than the nav bars.  I suspect on the dashboard it could show up where the integration and connections lists are, so we'll probably want to revisit that.  There's a refresh button and a link to the syndesis issue tracker on it when it appears.  Eventually I think it'd be good to also have a button that shows the server error.
