### ISSUE TITLE
Refactor IIntegrationAction for reuse

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-react#204]
## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
This issue is being opened in relation to this PR feedback: https://github.com/syndesisio/syndesis-react/pull/137#discussion_r279668207

`IIntegrationAction` is used in more than one area and should be refactored.

**Comment by gashcrumb** [comment]
I actually had already created https://github.com/syndesisio/syndesis-react/issues/196 for this...
