### ISSUE TITLE
Auto-collapse IVP when in Integration Editor 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis-react#206]
## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

IVP should auto-collapse when users are in Integration Editor to allow for optimal presentation for the create integration workflow. 

<img width="1439" alt="Screen Shot 2019-04-30 at 1 15 33 PM" src="https://user-images.githubusercontent.com/24943812/56980363-23917d00-6b4a-11e9-9a91-df4cb1a42d52.png">

**Comment by amysueg** [comment]
@dongniwang just to clarify - do you mean that the left vertical nav should collapse when the user is editing/creating an integration?

**Comment by dongniwang** [comment]
@amysueg - yes.
