### ISSUE TITLE
Connections list page: disabled 'delete' menu item still triggers a delete confirmation

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-react#208]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Spotted it, so logging it:

![image](https://user-images.githubusercontent.com/351660/56988234-8b04f800-6b5d-11e9-8ea0-48b0e52b9eb8.png)

**Comment by gashcrumb** [comment]
probably this menu item should use a button link, as you can't actually disable an anchor tag.

**Comment by elvisisking** [comment]
Fixed by #374
