### ISSUE TITLE
NS_ERROR_ILLEGAL_VALUE on firefox when clicking the 'Edit' menu item

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-react#211]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Seems to be firefox specific:

![image](https://user-images.githubusercontent.com/351660/57029612-44240a80-6c10-11e9-8105-33e4580e0abd.png)

**Comment by riccardo-forina** [comment]
Wonder, is the flow’s id url-safe?

**Comment by gashcrumb** [comment]
I think it is actually at least am looking at a page in the editor on chrome and:

`http://localhost:3000/integrations/i-LSoZITwNEGxnyKOp70Mz/edit/-LSoZAP95joM62_H97mR/1/add/`

is there a chance maybe we're trying to push an empty string onto the URL history perhaps?  That's the odd thing that strikes me about how this is showing up, but I haven't looked to far into it yet, I just switched to chrome for now and logged this to deal with in the future :-)

**Comment by riccardo-forina** [comment]
Ah, I think it's the integration object passed in the state that's too big...

**Comment by riccardo-forina** [comment]
This is the JSON evaluation for the FHIR integration we have on staging, that's one that's giving me the problem.

![image](https://user-images.githubusercontent.com/966316/57066914-d807dc00-6ccd-11e9-88e0-e4ec69250958.png)

It looks like we are paying the cost of embedding the specification for the connector that, in the FHIR case, consists in the full XML with license and everything https://gist.github.com/riccardo-forina/f671a2257db87fc2464dc9f14e308fb8

This is a breaking problem for us, the way the editor works right now assumes the integration object to be passed around at every step together with the link...

**Comment by gashcrumb** [comment]
Hmm, data mapper config can probably get really large as well.  Also I forget, do we embed the actual swagger for API provider integrations?  I think generally yeah that specification field can contain XML or a stringified representation of java code, so unbounded.  Unfortunately this is something we'll have to figure out how to deal with :-(
