### ISSUE TITLE
Empty integration history item actions 

### ISSUE THREAD

**Issue by riccardo-forina** [syndesisio/syndesis-react#221]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

The dropdown menu for history entries in the History tab of the Integration Details page always renders empty. Checking staging it should show:

* Publish/Unpublish
* Replace Draft

Not sure if there are scenarios with other entries.

**Comment by gashcrumb** [comment]
Yeah, those need to be hooked up still.
