### ISSUE TITLE
Skip hooks if deleting branch remotely

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-react#247]
## This is a...

<pre><code>
[ x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

If you want to delete your Git branches from the terminal using `git push origin :<branch>` or `git push origin --delete <branch>`, you should be able to without all the hooks. Maybe we can use regex to check the issued command.

**Comment by riccardo-forina** [comment]
Can't you append a `--no-verify` when doing that?

I personally remove the branch once a PR of mine gets merged, and then run `git remote prune origin` to keep my local checkout in sync with whatever I have on GH.

**Comment by kahboom** [comment]
Hmm good point, I always forget about `--no-verify` since I try to avoid it. Think this is a bit of an exception. 👍
