### ISSUE TITLE
Editor - Implement the data mapper step

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-react#252]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
We need to move the example data mapper into a step configuration page (finally :smile:) The data mapper step doesn't contain a properties object, but it does [create](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts#L326-L344) an `action` attribute that has data shape information.  The data mapper component supplies a [save handler callback](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts#L382-L395) that is used to update the `configuredProperties` attribute on the step.

The data mapper component requires a [ton of inputs](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts#L491-L527) to operate correctly.  The host component [builds a list](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts#L122) of input documents using the output data shapes of previous steps in the integration flow and [creates](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/step-configure/data-mapper/data-mapper-host.component.ts#L123) a target document that reflects the input data shape of the subsequent step that has one.

Hopefully a lot of the angular code that initializes the data mapper could be carried forward into our adapter, then on the react side we could create a cleaner interface to send/receive data.

**Comment by gashcrumb** [comment]
@riccardo-forina you're working on this, right?  Unassign if not :-)

**Comment by gashcrumb** [comment]
I guess this is like done, right?

**Comment by riccardo-forina** [comment]
Think so, yeah! Forgot to close.
