### ISSUE TITLE
Editor - Implement the conditional flow step

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-react#255]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
We'll need to port [this PR](https://github.com/syndesisio/syndesis/pull/5322)

**Comment by gashcrumb** [comment]
And [this pr](https://github.com/syndesisio/syndesis/pull/5339)

**Comment by gashcrumb** [comment]
And also [this PR](https://github.com/syndesisio/syndesis/pull/5342#pullrequestreview-236864935)

**Comment by gashcrumb** [comment]
And [this PR](https://github.com/syndesisio/syndesis/pull/5375) too

**Comment by gashcrumb** [comment]
[related changes](https://github.com/syndesisio/syndesis/pull/5380)

**Comment by gashcrumb** [comment]
[this is relevant](https://github.com/syndesisio/syndesis/pull/5450) too probably

**Comment by gashcrumb** [comment]
[and this](https://github.com/syndesisio/syndesis/pull/5451)

**Comment by gashcrumb** [comment]
@christophd hey, BTW do you have any good conditional flow integration exports you could share?

**Comment by christophd** [comment]
sure, will share this via mail with you

**Comment by gashcrumb** [comment]
[this too](https://github.com/syndesisio/syndesis/pull/5509#issuecomment-497079391)

**Comment by riccardo-forina** [comment]
Maybe reopen?

**Comment by gashcrumb** [comment]
[another thing](https://github.com/syndesisio/syndesis/pull/5554)
