### ISSUE TITLE
Make "Publish" in integration flow either link or button not both 

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis-react#276]
Currently "Publish" Button is a link in integration flow except last page. There is a button. This complicates test migration. 

![screenshot_20190514_102650](https://user-images.githubusercontent.com/6814482/57682827-dd9ce480-7632-11e9-8448-2297dfea5f7d.png)

![screenshot_20190514_102705](https://user-images.githubusercontent.com/6814482/57682844-e4c3f280-7632-11e9-8e68-00d03cafa6fa.png)

**Comment by gashcrumb** [comment]
Would it help if we stick IDs on those buttons?  

Part of the reason why it switches is `disabled` doesn't disable an anchor tag, and on that first page they're links to bring you to that second page to fill in the name/description.

**Comment by mmelko** [comment]
Yeah sure, ID is the best. I could live with ID's everywhere :)

**Comment by gashcrumb** [comment]
Perfect, I added `integration-editor-*-button` Ids to the relevant `cancel`, `save`, and `publish` buttons in that PR.  And if you need IDs on other buttons just open an issue, they generally should be easy enough to add.
