### ISSUE TITLE
Need react version of providing user info

### ISSUE THREAD

**Issue by vhalbert** [syndesisio/syndesis-react#278]
## This is an enhancement

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

DV needs access to the userinfo.    @gashcrumb has pointed to the following that could be ported over:
 https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/core/providers/user-provider.service.ts#L24

**Comment by gashcrumb** [comment]
@seanforyou23 FYI we'll need this also for showing the right user in the nav bar.

**Comment by gashcrumb** [comment]
I'd probably create a `WithUser` component that just makes the response from `/users/~` available.  It'll be a lot like [this one](https://github.com/syndesisio/syndesis-react/blob/master/app/ui-react/packages/api/src/WithApiVersion.tsx) as the API just returns a simple object that looks like `{ username: "foo" }` afaik.  

For logout eventually I'd probably create a `WithUserHelpers` and it'd look similar to [this file](https://github.com/syndesisio/syndesis-react/blob/master/app/ui-react/packages/api/src/WithEnvironmentHelpers.tsx#L18) and put the code for logout in there ultimately.  But I'd say focus on `WithUsers` for this issue.

**Comment by gashcrumb** [comment]
Also we could probably just set this user in [the AppContext](https://github.com/syndesisio/syndesis-react/blob/master/app/ui-react/syndesis/src/app/AppContext.tsx#L5) using `WithUser` by adding it around [here](https://github.com/syndesisio/syndesis-react/blob/master/app/ui-react/syndesis/src/app/App.tsx#L65), that way we don't need to invoke that API, instead code that needs the user name can use an `AppContext.Consumer`.

**Comment by riccardo-forina** [comment]
> Also we could probably just set this user in [the AppContext](https://github.com/syndesisio/syndesis-react/blob/master/app/ui-react/syndesis/src/app/AppContext.tsx#L5) [](/syndesisio/syndesis-react/blob/HEAD@{2019-05-14T15:26:39Z}/app/ui-react/syndesis/src/app/AppContext.tsx#L5) using `WithUser` by adding it around [here](https://github.com/syndesisio/syndesis-react/blob/master/app/ui-react/syndesis/src/app/App.tsx#L65) [](/syndesisio/syndesis-react/blob/HEAD@{2019-05-14T15:26:39Z}/app/ui-react/syndesis/src/app/App.tsx#L65), that way we don't need to invoke that API, instead code that needs the user name can use an `AppContext.Consumer`.

+1
