### ISSUE TITLE
Unsupported Media Type when uploading extension .jar file

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis-react#279]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Upload of extension doesn't work. It was working before. 
![screenshot_20190514_155545](https://user-images.githubusercontent.com/6814482/57703767-fde39800-7660-11e9-8a18-206206e0024f.png)

**Comment by riccardo-forina** [comment]
That looks like an error sent from the backend. Does it happen when using the Angular app too?

**Comment by mmelko** [comment]
Nope, with Angular app it's working fine.
