### ISSUE TITLE
Next button is active only after Period interaction in Simple Timer action

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis-react#286]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Currently when I have Timer as start connection and I select 'Simple Timer' I have to interact with 'Period' otherwise 'Next' is inactive. I have to do this even if I want to keep the default value. 
![screenshot_20190515_113243](https://user-images.githubusercontent.com/6814482/57765198-418fdd80-7705-11e9-9829-3fb25ca5d2f4.png)

**Comment by riccardo-forina** [comment]
Yes we have [an open issue](https://github.com/syndesisio/syndesis-react/issues/270) for that.
