### ISSUE TITLE
Integration won't start publishing

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis-react#288]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Integration won't start publishing. This is clearly not done yet, but I haven't seen it in Trello board.
![screenshot_20190515_152059](https://user-images.githubusercontent.com/6814482/57778903-5714ff80-7725-11e9-901d-586fcdb93783.png)
![screenshot_20190515_152350](https://user-images.githubusercontent.com/6814482/57778948-77dd5500-7725-11e9-8ecc-85b08f43a69c.png)

**Comment by gashcrumb** [comment]
We lumped this into the XL editor card, just added this as a line item -> https://trello.com/c/08dwBrtI/7-xl-integration-editor
