### ISSUE TITLE
Recent Updates - support error handling

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis-react#293]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

See screenshot. `RecentUpdatesCard` component does not support errors at networking level like some other components do.

See https://github.com/syndesisio/syndesis-react/blob/638933e7c2e5ea912c7b079bfe5bc7aeced64d01/app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx#L225

![Screenshot from 2019-05-16 10-24-04](https://user-images.githubusercontent.com/1520602/57839250-a0695b80-77c6-11e9-8f4b-1d225a6509c5.png)

**Comment by elvisisking** [comment]
This was fixed by #367
