### ISSUE TITLE
Implement icon upload in API Client Connector edit page

### ISSUE THREAD

**Issue by elvisisking** [syndesisio/syndesis-react#296]
## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
File upload of icon files needs to be implemented. New icons are saved when the edit page is saved.

**Comment by riccardo-forina** [comment]
This is done now, right?

**Comment by elvisisking** [comment]
Yes @riccardo-forina fixed by #306
