### ISSUE TITLE
[extensions actions] is there any reason why update is a link element and delete a button?

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis-react#337]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

**Comment by gashcrumb** [comment]
navigation vs triggering an action, `update` takes you to a different page vs `delete` which uses an `onClick`.  So, probably best to get ids on these elements rather than try and change them.

**Comment by gashcrumb** [comment]
Hopefully this answered your question alright, let us know if we need to change something.
