### ISSUE TITLE
describe-data routing appears to lose the correct step index

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-react#348]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Noticed this when testing out something else, so to reproduce create an integration using an AMQ connection.  Use "Subscribe for messages" and you'll be at this config page:

![image](https://user-images.githubusercontent.com/351660/58268986-8692c000-7d54-11e9-8296-3e80517117f0.png)

'Next' takes you to the "describe data page" but look at what happens in the side-bar:

![image](https://user-images.githubusercontent.com/351660/58269047-a75b1580-7d54-11e9-8158-5564dc6c6019.png)

Then when I click next again:

![image](https://user-images.githubusercontent.com/351660/58269070-bcd03f80-7d54-11e9-9246-a2b3ef020b1a.png)

so I think now I'm filling in the end step, but I picked something:

![image](https://user-images.githubusercontent.com/351660/58269142-e8ebc080-7d54-11e9-9093-915b7c455b6a.png)

And now we're here:

![image](https://user-images.githubusercontent.com/351660/58269313-454ee000-7d55-11e9-92f8-8d861523680a.png)

the last step there doesn't seem to edit properly either, in that if I change the action to an appropriate one I don't wind up at the describe data page after the configuration page.

**Comment by mmelko** [comment]
This also complicates to use Datamapper.
