### ISSUE TITLE
Uncaught exception configuring a step 

### ISSUE THREAD

**Issue by riccardo-forina** [syndesisio/syndesis-react#362]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

![image](https://user-images.githubusercontent.com/966316/58539610-02c75080-81f8-11e9-8d1f-f4977d1171b5.png)

Introduced by #358 I think (cc @gashcrumb, sorry, I didn't notice this before approving).

**Comment by gashcrumb** [comment]
No worries I'll look in a few.
