### ISSUE TITLE
Integration configure the action page - default selection in dropdown is "Accepted Event Relation" 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis-react#377]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I was trying to configure a Salesforce action and the "next" button is disabled until I make a selection other than the "Accepted Event Relation" option. 

See screenshot below. 

<img width="1428" alt="Screen Shot 2019-05-30 at 3 27 33 PM" src="https://user-images.githubusercontent.com/24943812/58659316-ab58db80-82f0-11e9-82da-76d4c72a8956.png">

cc: @gashcrumb

**Comment by dongniwang** [comment]
Got this page after making the selection from the dropdown and clicked Next. I was told that this is could be a similar bug with the select control. 

<img width="591" alt="Screen Shot 2019-05-30 at 3 42 57 PM" src="https://user-images.githubusercontent.com/24943812/58660088-90876680-82f2-11e9-9833-22f2c3995ba8.png">

cc: @gashcrumb @riccardo-forina

**Comment by gashcrumb** [comment]
@dongniwang while fixing the 'next' button there, I've found that indeed this second issue you saw is a different bug altogether.  Looks like we aren't using the backend response for the form when we move to the second page of configuration.  I'll see if I can just fix this also now.

**Comment by gashcrumb** [comment]
On second thought, I'm gonna create a new issue for the second comment.

**Comment by gashcrumb** [comment]
Created https://github.com/syndesisio/syndesis-react/issues/382 for that second issue @dongniwang
