### ISSUE TITLE
💄 Log page Truncation

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis-react#395]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Documentation issue or request
</code></pre>

<img width="1421" alt="Screen Shot 2019-06-03 at 10 54 28" src="https://user-images.githubusercontent.com/674767/58827476-1ff18a00-8611-11e9-8372-8ff602f817ad.png">

**Comment by dongniwang** [comment]
@mcoker - is this something you can take a look at? I think you mention text wrap. And if it's possible, please make sure we are wrapping properly for content in a table view. Thanks!
