### ISSUE TITLE
💄 Main landing page truncation

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis-react#399]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

<img width="602" alt="Screen Shot 2019-06-03 at 14 44 35" src="https://user-images.githubusercontent.com/674767/58827908-30eecb00-8612-11e9-8a14-a8748e20a92a.png">

**Comment by paoloantinori** [comment]
That looks really bad. Which resolution are you using?
Is the window maximized?

**Comment by gaughan** [comment]
not maximized, 2560 x 1600

**Comment by gashcrumb** [comment]
Yeah, I see this all the time, I've 3 1080p monitors (yes I know, time to upgrade) and tend not to maximize and it always looks like:

![image](https://user-images.githubusercontent.com/351660/59108031-fe8de800-8907-11e9-9c6d-e02f98dff4ac.png)

**Comment by gashcrumb** [comment]
Feels like if we could dump the 'configuration required' text that'd go a long way :-)
