### ISSUE TITLE
💄 Integration editor UI issues in small screens

### ISSUE THREAD

**Issue by mcoker** [syndesisio/syndesis-react#401]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
If you go to pages that use `.integration-editor-layout` (create connection, create api connector, integration editor), there are layout issues on a small screen. @riccardo-forina wanted to ping you to see if this is something you'd like to fix since it looks like you work with this a lot, or if you'd like me to look into it.

## Screenshot
<img width="715" alt="Screen Shot 2019-06-03 at 2 33 39 PM" src="https://user-images.githubusercontent.com/35148959/58829366-47465800-860d-11e9-9766-359c6f0cc2f1.png">

<img width="773" alt="Screen Shot 2019-06-03 at 10 44 27 AM" src="https://user-images.githubusercontent.com/35148959/58829346-3bf32c80-860d-11e9-8609-a3bfffe7c4f6.png">

<img width="755" alt="Screen Shot 2019-06-03 at 2 33 05 PM" src="https://user-images.githubusercontent.com/35148959/58829415-5d541880-860d-11e9-9e2e-225f5bd895d3.png">

<img width="718" alt="Screen Shot 2019-06-03 at 2 34 51 PM" src="https://user-images.githubusercontent.com/35148959/58829427-61803600-860d-11e9-9e7f-9d9ba31a5ba3.png">
<img width="699" alt="Screen Shot 2019-06-03 at 2 34 59 PM" src="https://user-images.githubusercontent.com/35148959/58829434-65ac5380-860d-11e9-9dfc-7d13ead6530c.png">
<img width="717" alt="Screen Shot 2019-06-03 at 2 36 45 PM" src="https://user-images.githubusercontent.com/35148959/58829438-693fda80-860d-11e9-9d3e-746b7a10e69c.png">

## Request and Response Data
<!--
Many issues involve both the UI and its backend, if possible capture relevant request and response data JSON messages and include it here.
Request and response data can be gathered from your browser's developer tools on the 'Network' tab.
 + As you reproduce the issue, take note of any network requests that are made.
 + Requests that result in an error will be highlighted red.
 + Click on line in the network tab and then the 'Headers' tab to get the request data
 + Click on the 'Preview' or 'Response' tabs to get the response data.
 + Pretty print the json too -> http://jsonprettyprint.com/

cc @dongniwang @lboehling @seanforyou23

**Comment by riccardo-forina** [comment]
Oh feel free to give it a stab if you want! This guy here is the layout bit that’s in common between all editors https://github.com/syndesisio/syndesis-react/blob/master/app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorLayout.css
