### ISSUE TITLE
Editor - Unknown conditional flow listed in the API provider breadcrumb dropdown 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis-react#408]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

In an API provider integration, when trying to navigate to a different flow, I saw an unknown "a Conditional Flow" listed in the breadcrumb operation list dropdown. 

I don't think that conditional flow should show up in the dropdown? Or we need a way to separate these sub-flows? 

<img width="550" alt="Screen Shot 2019-06-04 at 10 34 21 AM" src="https://user-images.githubusercontent.com/24943812/58888170-fc801b00-86b4-11e9-80dd-65245738b680.png">

**Comment by gashcrumb** [comment]
This PR will fix this -> https://github.com/syndesisio/syndesis-react/pull/402
