### ISSUE TITLE
Integration Detail Page Layout

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-react#58]
### Details tab

* [ ] implementation
* [ ] write storybooks
* [ ] write tests

### Activity tab

* [ ] implementation
* [ ] write storybooks
* [ ] write tests

### Metrics tab

* [ ] implementation
* [ ] write storybooks
* [ ] write tests

Should also probably add the route, unless @riccardo-forina has done this

### integration details route (/integrations/:integrationId/details)

* [ ] page component
* [ ] set up the i18n labels
* [ ] write tests

**Comment by riccardo-forina** [comment]
Yep it makes sense!
