### ISSUE TITLE
Customization: Extensions page layout

### ISSUE THREAD

**Issue by elvisisking** [syndesisio/syndesis-react#78]
Implementation of the UI related to extensions.

### list
* [x]  implementation
* [x]  write storybooks
* [x]  write tests

### list empty page layout
* [x]  implementation
* [x]  write storybooks
* [x]  write tests

### extension details page layout
* [x]  implementation
* [x]  write storybooks
* [x]  write tests

### extension import page layout
* [x]  implementation
* [x]  write storybooks
* [x]  write tests

See syndesisio/syndesis#4043

**Comment by gashcrumb** [comment]
This is like, done, isn't it?

**Comment by elvisisking** [comment]
Yes. I have finished stories and jest tests.
